name: Manually Deploy to Heroku L

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          HEROKU_API_KEY: "HRKU-2cb7f626-d0a4-4a61-b923-5e99556ea0d0"
          HEROKU_APP_NAME: "altet"
          HEROKU_EMAIL: "publicmay@@povkx.me" 


          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"

        
